### ISSUE TITLE
removeAllResources() does not work

### ISSUE THREAD

**Issue by martinjinda** [K15t/gulp-viewport#2]
Hi,
recently I have a problem with this function and I always get following error:

```
[14:52:34] Using gulpfile ~/devel/folder/gulpfile.js
[14:52:34] Starting 'delete-theme'...
[14:52:34] 'delete-theme' errored after 279 μs
[14:52:34] ReferenceError: that is not defined
    at removeAllResources (/Users/martinjinda/devel/folder/node_modules/gulp-viewport/index.js:142:9)
    at Gulp.<anonymous> (/Users/martinjinda/devel/folder/gulpfile.js:35:16)
    at module.exports (/Users/martinjinda/devel/folder/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/martinjinda/devel/folder/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/martinjinda/devel/folder/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/martinjinda/devel/folder/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
    at Function.Module.runMain (module.js:469:11)
```

I solved it with one line to your gulpfile.js:

```
function removeAllResources(uploadOpts) {

    var that = this;
    ...
```

**Comment by jefft** [comment]
Hit the same problem - thanks for suggesting the fix.

**Comment by MartinMuzatko** [comment]
This should be fixed with the latest release.
